export const SPECIALS = [
  {
    id: 1,
    name: "Flame Burst",
    effect: (power) =>
      `Deals ${power * 100}% ATK damage and burns the target (loses ${power}% HP per turn).`,
    cooldown: 4,
    cooldownType: "turn",
    usingType: "manual",
    power: 4.5,
    image: "flame_burst.png",
  },
  {
    id: 2,
    name: "Aqua Shield",
    effect: (power) =>
      `Creates a water shield absorbing damage equal to ${power * 100}% of max HP.`,
    cooldown: 5,
    cooldownType: "turn",
    usingType: "auto",
    power: 0.1,
    image: "aqua_shield.png",
  },
  {
    id: 3,
    name: "Thunder Strike",
    effect: (power) =>
      `Deals ${power * 100}% ATK damage with a 40% chance to stun for 1 turn.`,
    cooldown: 3,
    cooldownType: "level",
    usingType: "manual",
    power: 1.3,
    image: "thunder_strike.png",
  },
  {
    id: 4,
    name: "Healing Light",
    effect: (power) => `Heals ${power * 100}% HP for self or an ally.`,
    cooldown: 4,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.3,
    image: "healing_light.png",
  },
  {
    id: 5,
    name: "Poison Cloud",
    effect: (power) =>
      `Poisons all enemies, dealing ${power * 100}% HP as damage per turn for 4 turns.`,
    cooldown: 6,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.05,
    image: "poison_cloud.png",
  },
  {
    id: 6,
    name: "Battle Roar",
    effect: (power) =>
      `Increases team attack by ${power * 100}% for 3 turns.`,
    cooldown: 5,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.25,
    image: "battle_roar.png",
  },
  {
    id: 7,
    name: "Stone Skin",
    effect: (power) =>
      `Increases armor by ${power * 100}% for 2 turns.`,
    cooldown: 4,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.4,
    image: "stone_skin.png",
  },
  {
    id: 8,
    name: "Shadow Step",
    effect: (power) =>
      `Increases evasion and attack by ${power * 100}% for the next turn.`,
    cooldown: 3,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.2,
    image: "shadow_step.png",
  },
  {
    id: 9,
    name: "Frost Nova",
    effect: (power) =>
      `Deals ${power * 100}% damage to all enemies and slows them by ${power * 100}% for 2 turns.`,
    cooldown: 5,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.3,
    image: "frost_nova.png",
  },
  {
    id: 10,
    name: "Divine Blessing",
    effect: () =>
      `Restores the user's state but reduces defense by 25% for 5 turns.`,
    cooldown: 25,
    cooldownType: "turn",
    usingType: "manual",
    power: null,
    image: "divine_blessing.png",
  },
  {
    id: 11,
    name: "Death Mark",
    effect: () => `Marks the target, increasing damage taken by 50% for 3 turns.`,
    cooldown: 12,
    cooldownType: "turn",
    usingType: "manual",
    power: null,
    image: "death_mark.png",
  },
  {
    id: 12,
    name: "Blazing Tornado",
    effect: (power) =>
      `Deals ${power * 100}% ATK damage to all enemies with a 30% chance to burn for 2 turns.`,
    cooldown: 6,
    cooldownType: "turn",
    usingType: "manual",
    power: 1.2,
    image: "blazing_tornado.png",
  },
  {
    id: 13,
    name: "Spirit Drain",
    effect: (power) =>
      `Drains ${power * 100}% HP from the target and restores it to the user.`,
    cooldown: 5,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.2,
    image: "spirit_drain.png",
  },
  {
    id: 14,
    name: "Iron Will",
    effect: (power) =>
      `Grants immunity to debuffs for 2 turns and increases defense by ${power * 100}%.`,
    cooldown: 6,
    cooldownType: "turn",
    usingType: "auto",
    power: 0.15,
    image: "iron_will.png",
  },
  {
    id: 15,
    name: "Berserk",
    effect: (power) =>
      `Increases power by ${power * 100}% for 1 turn. When it ends, stunned and loses 20% current HP.`,
    cooldown: 9,
    cooldownType: "turn",
    usingType: "manual",
    power: 3,
    image: "berserk.png",
  },
  {
    id: 16,
    name: "Venom Fang",
    effect: (power) =>
      `Deals ${power * 100}% ATK damage with a 20% chance to poison the target for 3 turns.`,
    cooldown: 3,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.8,
    image: "venom_fang.png",
  },
  {
    id: 17,
    name: "Celestial Heal",
    effect: (power) =>
      `Heals all allies by ${power * 100}% HP and removes all debuffs.`,
    cooldown: 20,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.3,
    image: "celestial_heal.png",
  },
];
