export const SPECIALS = [
  {
    id: 1,
    name: "Flame Burst",
    effect:
      "Gây 450% sát thương tấn công và đốt cháy kẻ địch (mất 4.5% HP mỗi lượt).",
    cooldown: 4,
    cooldownType: "turn",
    usingType: "manual",
    power: 4.5,
    image: "flame_burst.png",
  },
  {
    id: 2,
    name: "Aqua Shield",
    effect:
      "Tạo lá chắn nước hấp thụ sát thương bằng 10% HP tối đa.",
    cooldown: 5,
    cooldownType: "turn",
    usingType: "auto",
    power: 0.1,
    image: "aqua_shield.png",
  },
  {
    id: 3,
    name: "Thunder Strike",
    effect:
      "Tấn công mục tiêu với 130% sát thương và có 40% làm tê liệt 1 lượt.",
    cooldown: 3,
    cooldownType: "level",
    usingType: "manual",
    power: 1.3,
    image: "thunder_strike.png",
  },
  {
    id: 4,
    name: "Healing Light",
    effect: "Hồi phục 30% HP cho bản thân hoặc đồng minh.",
    cooldown: 4,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.3,
    image: "healing_light.png",
  },
  {
    id: 5,
    name: "Poison Cloud",
    effect:
      "Tạo đám độc gây 10% HP sát thương mỗi lượt trong 4 lượt cho toàn bộ kẻ địch.",
    cooldown: 6,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.1,
    image: "poison_cloud.png",
  },
  {
    id: 6,
    name: "Battle Roar",
    effect: "Tăng 25% tấn công cho toàn đội trong 3 lượt.",
    cooldown: 5,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.25,
    image: "battle_roar.png",
  },
  {
    id: 7,
    name: "Stone Skin",
    effect: "Giảm 40% sát thương nhận vào trong 2 lượt.",
    cooldown: 4,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.4,
    image: "stone_skin.png",
  },
  {
    id: 8,
    name: "Shadow Step",
    effect: "Tránh né đòn kế tiếp và tăng 20% tấn công ở lượt sau.",
    cooldown: 3,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.2,
    image: "shadow_step.png",
  },
  {
    id: 9,
    name: "Frost Nova",
    effect:
      "Gây 100% sát thương cho tất cả kẻ địch và làm chậm 30% tốc độ trong 2 lượt.",
    cooldown: 5,
    cooldownType: "turn",
    usingType: "manual",
    power: 1.0,
    image: "frost_nova.png",
  },
  {
    id: 10,
    name: "Divine Blessing",
    effect: "Loại bỏ tất cả hiệu ứng xấu và tăng 15% phòng thủ trong 3 lượt.",
    cooldown: 6,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.15,
    image: "divine_blessing.png",
  },
  {
    id: 11,
    name: "Death Mark",
    effect: "Đánh dấu mục tiêu: nhận thêm 30% sát thương trong 3 lượt.",
    cooldown: 5,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.3,
    image: "death_mark.png",
  },
  {
    id: 12,
    name: "Blazing Tornado",
    effect:
      "Tạo lốc lửa tấn công toàn bộ kẻ địch với 120% sát thương và có 30% cơ hội đốt cháy 2 lượt.",
    cooldown: 6,
    cooldownType: "turn",
    usingType: "manual",
    power: 1.2,
    image: "blazing_tornado.png",
  },
  {
    id: 13,
    name: "Spirit Drain",
    effect:
      "Hút 20% HP và 10% năng lượng từ mục tiêu, chuyển thành máu cho bản thân.",
    cooldown: 5,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.2,
    image: "spirit_drain.png",
  },
  {
    id: 14,
    name: "Iron Will",
    effect: "Miễn nhiễm hiệu ứng xấu trong 2 lượt và tăng 15% phòng thủ.",
    cooldown: 6,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.15,
    image: "iron_will.png",
  },
  {
    id: 15,
    name: "Arcane Overload",
    effect:
      "Tăng 50% sức mạnh phép thuật trong 1 lượt, sau đó giảm 10% HP do phản chấn.",
    cooldown: 4,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.5,
    image: "arcane_overload.png",
  },
  {
    id: 16,
    name: "Venom Fang",
    effect:
      "Cắn độc gây 80% sát thương và 20% cơ hội khiến mục tiêu bị trúng độc 3 lượt.",
    cooldown: 3,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.8,
    image: "venom_fang.png",
  },
  {
    id: 17,
    name: "Celestial Heal",
    effect: "Hồi 40% HP cho toàn đội và xoá 1 hiệu ứng xấu ngẫu nhiên.",
    cooldown: 7,
    cooldownType: "turn",
    usingType: "manual",
    power: 0.4,
    image: "celestial_heal.png",
  },
];
