export const rawConfigs = {
  "agathe/default": {
    width: 128,
    height: 128,
    layers: {
      player: {
        frameCount: 3,
        speed: 240,
        delay: 0,
        flip: true,
        moving: false,
      },
      front: {
        frameCount: 5,
        speed: 240,
      },
      slash: {
        frameCount: 4,
        speed: 120,
        delay: 480,
        flip: true,
        moving: false,
        movingFrameCount: 5,
        moveStopDistance: 250,
      },
    },
  },
  "agathe/heretic_punisher_captain": {
    width: 128,
    height: 128,
    layers: {
      player: {
        frameCount: 3,
        speed: 240,
        delay: 0,
        flip: true,
        moving: false,
      },
      front: {
        frameCount: 5,
        speed: 240,
      },
      slash: {
        frameCount: 4,
        speed: 120,
        delay: 480,
        flip: true,
        moving: false,
        movingFrameCount: 5,
        moveStopDistance: 250,
      },
    },
  },
  "agathe/undead": {
    width: 128,
    height: 128,
    layers: {
      player: {
        frameCount: 3,
        speed: 240,
        delay: 0,
        flip: true,
        moving: false,
      },
      front: {
        frameCount: 5,
        speed: 240,
      },
      slash: {
        frameCount: 4,
        speed: 120,
        delay: 480,
        flip: true,
        moving: false,
        movingFrameCount: 5,
        moveStopDistance: 250,
      },
    },
  },
  "agathe/pristine_winter": {
    width: 128,
    height: 128,
    layers: {
      player: {
        frameCount: 3,
        speed: 240,
        delay: 0,
        flip: true,
        moving: false,
      },
      front: {
        frameCount: 5,
        speed: 240,
      },
      slash: {
        frameCount: 4,
        speed: 120,
        delay: 480,
        flip: true,
        moving: false,
        movingFrameCount: 5,
        moveStopDistance: 250,
      },
    },
  },
  "agathe/knight": {
    width: 128,
    height: 128,
    layers: {
      player: {
        frameCount: 3,
        speed: 240,
        delay: 0,
        flip: true,
        moving: false,
      },
      front: {
        frameCount: 5,
        speed: 240,
      },
      slash: {
        frameCount: 4,
        speed: 120,
        delay: 480,
        flip: true,
        moving: false,
        movingFrameCount: 5,
        moveStopDistance: 250,
      },
    },
  },
  "bardrey/default": {
    width: 128,
    height: 128,
    layers: {
      player: {
        frameCount: 3,
        speed: 240,
        delay: 0,
        flip: true,
        moving: false,
        stopMovingAtFrame: 3,
      },
      front: {
        frameCount: 5,
        speed: 240,
      },
      slash: {
        frameCount: 8,
        speed: 120,
        delay: 180,
        flip: false,
        moving: true,
        movingFrameCount: 5,
        moveStopDistance: 250,
      },
    },
  },
  "alberon/default": {
    width: 128,
    height: 128,
    layers: {
      player: {
        frameCount: 3,
        speed: 240,
        delay: 0,
        flip: true,
        moving: false,
        stopMovingAtFrame: 3,
      },
      front: {
        frameCount: 5,
        speed: 240,
      },
      slash: {
        frameCount: 5,
        speed: 120,
        delay: 180,
        flip: false,
        moving: true,
        movingFrameCount: 1,
        moveStopDistance: 250,
      },
    },
  },
  "alberon/holy_king": {
    width: 128,
    height: 128,
    layers: {
      player: {
        frameCount: 3,
        speed: 240,
        delay: 0,
        flip: true,
        moving: false,
        stopMovingAtFrame: 3,
      },
      front: {
        frameCount: 5,
        speed: 240,
      },
      slash: {
        frameCount: 7,
        speed: 120,
        delay: 180,
        flip: false,
        moving: true,
        movingFrameCount: 1,
        moveStopDistance: 250,
      },
    },
  },
  "esthea/default": {
    width: 128,
    height: 128,
    layers: {
      player: {
        frameCount: 3,
        speed: 240,
        delay: 0,
        flip: true,
        moving: false,
        stopMovingAtFrame: 3,
      },
      front: {
        frameCount: 5,
        speed: 240,
      },
      slash: {
        frameCount: 10,
        speed: 120,
        delay: 180,
        flip: false,
        moving: true,
        movingFrameCount: 4,
        moveStopDistance: 250,
      },
    },
  },
  "esthea/poison_apple": {
    width: 128,
    height: 128,
    layers: {
      player: {
        frameCount: 3,
        speed: 240,
        delay: 0,
        flip: true,
        moving: false,
        stopMovingAtFrame: 3,
      },
      front: {
        frameCount: 5,
        speed: 240,
      },
      slash: {
        frameCount: 7,
        speed: 120,
        delay: 180,
        flip: false,
        moving: true,
        movingFrameCount: 1,
        moveStopDistance: 250,
      },
    },
  },
  "gidnil/default": {
    width: 128,
    height: 128,
    layers: {
      player: {
        frameCount: 3,
        speed: 240,
        delay: 0,
        flip: true,
        moving: false,
        stopMovingAtFrame: 3,
      },
      front: {
        frameCount: 6,
        speed: 240,
      },
      slash: {
        frameCount: 4,
        speed: 120,
        delay: 480,
        flip: false,
        moving: false,
        movingFrameCount: 4,
        moveStopDistance: 250,
      },
    },
  },
  "haerang/default": {
    width: 128,
    height: 128,
    layers: {
      player: {
        frameCount: 3,
        speed: 240,
        delay: 0,
        flip: true,
        moving: false,
        stopMovingAtFrame: 3,
      },
      front: {
        frameCount: 5,
        speed: 240,
      },
      slash: {
        frameCount: 7,
        speed: 120,
        delay: 180,
        flip: false,
        moving: true,
        movingFrameCount: 1,
        moveStopDistance: 250,
      },
    },
  },
  "hansi/default": {
    width: 128,
    height: 128,
    layers: {
      player: {
        frameCount: 4,
        speed: 180,
        delay: 0,
        flip: true,
        moving: false,
        stopMovingAtFrame: 3,
      },
      front: {
        frameCount: 5,
        speed: 180,
      },
      slash: {
        frameCount: 8,
        speed: 120,
        delay: 480,
        flip: false,
        moving: true,
        movingFrameCount: 3,
        moveStopDistance: 250,
      },
    },
  },
  "ian/default": {
    width: 128,
    height: 128,
    layers: {
      player: {
        frameCount: 4,
        speed: 240,
        delay: 0,
        flip: true,
        moving: false,
      },
      front: {
        frameCount: 7,
        speed: 240,
      },
      slash: {
        frameCount: 4,
        speed: 120,
        delay: 480,
        flip: true,
        moving: false,
        movingFrameCount: 5,
        moveStopDistance: 250,
      },
    },
  },
  "bombie/default": {
    width: 128,
    height: 128,
    layers: {
      player: {
        frameCount: 3,
        speed: 120,
        delay: 0,
        flip: true,
        moving: false,
        stopMovingAtFrame: 3,
      },
      front: {
        frameCount: 9,
        speed: 240,
      },
      slash: {
        frameCount: 9,
        speed: 120,
        delay: 180,
        flip: false,
        moving: true,
        movingFrameCount: 1,
        moveStopDistance: 250,
      },
    },
  },
  "jol/default": {
    width: 128,
    height: 128,
    layers: {
      player: {
        frameCount: 3,
        speed: 240,
        delay: 0,
        flip: true,
        moving: false,
      },
      front: {
        frameCount: 6,
        speed: 240,
      },
      slash: {
        frameCount: 5,
        speed: 120,
        delay: 480,
        flip: false,
        moving: false,
        movingFrameCount: 5,
        moveStopDistance: 250,
      },
    },
  },
  "kanak/default": {
    width: 128,
    height: 128,
    layers: {
      player: {
        frameCount: 3,
        speed: 120,
        delay: 0,
        flip: true,
        moving: false,
        stopMovingAtFrame: 3,
      },
      front: {
        frameCount: 6,
        speed: 240,
      },
      slash: {
        frameCount: 9,
        speed: 120,
        delay: 180,
        flip: false,
        moving: true,
        movingFrameCount: 1,
        moveStopDistance: 250,
      },
    },
  },
};