export const statIcons = {
  Health: {
    icon: "❤️",
    label: "Health",
    type: "flat",
    stackable: false,
    maxValue: null,
    desc: "Maximum hit points. If it reaches 0, you die.",
  },
  Regeneration: {
    icon: "💧",
    label: "Regeneration",
    type: "flat",
    stackable: true,
    maxValue: null,
    desc: "Amount of HP recovered each turn.",
  },
  Armor: {
    icon: "🛡️",
    label: "Armor",
    type: "flat",
    stackable: false,
    maxValue: null,
    desc: "Reduces incoming physical damage.",
  },
  Attack: {
    icon: "⚔️",
    label: "Attack",
    type: "flat",
    stackable: false,
    maxValue: null,
    desc: "Base damage dealt to enemies.",
  },
  "Crit Chance": {
    icon: "💥",
    label: "Crit Chance",
    type: "percent",
    stackable: false,
    maxValue: 1,
    desc: "Probability of landing a critical hit.",
  },
  "Crit Damage": {
    icon: "💣",
    label: "Crit Damage",
    type: "percent",
    stackable: false,
    maxValue: null,
    desc: "Extra damage multiplier when a crit occurs.",
  },
  "Life Steal": {
    icon: "🩸",
    label: "Life Steal",
    type: "percent",
    stackable: false,
    maxValue: 1,
    desc: "Portion of damage dealt returned as HP.",
  },
  Dodge: {
    icon: "💨",
    label: "Dodge",
    type: "percent",
    stackable: false,
    maxValue: 1,
    desc: "Chance to completely avoid an attack.",
  },
  Luck: {
    icon: "🍀",
    label: "Luck",
    type: "flat",
    stackable: false,
    maxValue: 99,
    desc: "Increases chances of finding rare items.",
  },
  Gold: {
    icon: "💰",
    label: "Gold",
    type: "flat",
    stackable: false,
    maxValue: null,
    desc: "Currency used to buy upgrades or items.",
  },
  Cooldown: {
    icon: "⏰",
    label: "Cooldown Reduction",
    type: "flat",
    stackable: false,
    maxValue: 99,
    desc: "Reduces the cooldown time of special abilities.",
  },
  Burn: {
    icon: "🔥",
    label: "Burn",
    type: "flat",
    stackable: false,
    maxValue: null,
    desc: "Deals fixed damage at the end of each turn.",
  },
  Poison: {
    icon: "💀",
    label: "Poison",
    type: "flat",
    stackable: true,
    maxValue: null,
    desc: "Deals damage each turn and increases over time.",
  },
  Thorn: {
    icon: "🌵",
    label: "Thorn",
    type: "flat",
    stackable: false,
    maxValue: null,
    desc: "Deals damage back when hit by an attack.",
  },
  Counterattack: {
    icon: "🤺",
    label: "Counterattack",
    type: "percent",
    stackable: false,
    maxValue: 1,
    desc: "Chance to attack back at the attacker when hit.",
  },
  "Stun Chance": {
    icon: "💫",
    label: "Stun Chance",
    type: "percent",
    stackable: false,
    maxValue: 1,
    desc: "Probability of disabling the enemy for one turn.",
  },
  Swiftness: {
    icon: "⚡",
    label: "Swiftness",
    type: "percent",
    stackable: false,
    maxValue: 1,
    desc: "Chance to perform a second attack in the same turn.",
  },
  Shield: {
    icon: "🩹",
    label: "Shield",
    type: "flat",
    stackable: false,
    maxValue: null,
    desc: "Temporary health at the start of each battle.",
  },
  Barrier: {
    icon: "🔰",
    label: "Barrier",
    type: "flat",
    stackable: false,
    maxValue: 999,
    desc: "Negates incoming attacks and is restored every battle.",
  },
  Immune: {
    icon: "😷",
    label: "Immune",
    type: "flat",
    stackable: false,
    maxValue: null,
    desc: "Grants immunity to all negative status effects.",
  },
  "Death Mark": {
    icon: "😵",
    label: "Death Mark",
    type: "flat",
    stackable: false,
    maxValue: null,
    desc: "Increases all incoming damage by 50%.",
  },

  Berserk: {
    icon: "😡",
    label: "Berserk",
    type: "flat",
    stackable: false,
    maxValue: null,
    desc: "When effect ends, stunned and loses 20% current health.",
  },
};
