export const allTypes = [
  "Colorless",
  "Darkness",
  "Dragon",
  "Fairy",
  "Fighting",
  "Fire",
  "Grass",
  "Lightning",
  "Metal",
  "Psychic",
  "Water",
];

export const allRarities = [
  "Common",
  "Uncommon",
  "Rare",
  "Rare Holo",
  "Rare Holo EX",
  "Rare Holo GX",
  "Rare Holo LV.X",
  "Rare Prime",
  "LEGEND",
  "Ultra Rare",
  "Double Rare",
  "ACE SPEC Rare",
  "Rare BREAK",
  "Promo",
  "Amazing Rare",
  "Radiant Rare",
  "Illustration Rare",
  "Special Illustration Rare",
  "Shiny Rare",
  "Shiny Ultra Rare",
  "Hyper Rare",
  "Rare ACE",
  "Rare Holo Star",
  "Rare Holo V",
  "Rare Holo VMAX",
  "Rare Holo VSTAR",
  "Rare Prism Star",
  "Rare Rainbow",
  "Rare Secret",
  "Rare Shining",
  "Rare Shiny",
  "Rare Shiny GX",
  "Rare Ultra",
  "Trainer Gallery Rare Holo",
  "Classic Collection",
];
