// ====================== Pokémon Constants ======================
export const allTypesPokemon = [
  "Water",
  "Grass",
  "Psychic",
  "Colorless",
  "Fighting",
  "Fire",
  "Lightning",
  "Darkness",
  "Metal",
  "Dragon",
  "Fairy",
];

export const allRaritiesPokemon = [
  "Common",
  "Uncommon",
  "Rare",
  "Rare Holo",
  "Promo",
  "Rare Ultra",
  "Rare Secret",
  "Rare Rainbow",
  "Rare Holo EX",
  "Rare Holo V",
  "Illustration Rare",
  "Ultra Rare",
  "Double Rare",
  "Rare Holo GX",
  "Special Illustration Rare",
  "Rare Shiny",
  "Shiny Rare",
  "Rare Holo VMAX",
  "Trainer Gallery Rare Holo",
  "Hyper Rare",
  "Rare Holo LV.X",
  "Rare Holo VSTAR",
  "Rare Shiny GX",
  "ACE SPEC Rare",
  "Rare Prism Star",
  "Rare BREAK",
  "Rare Prime",
  "Classic Collection",
  "Rare Holo Star",
  "LEGEND",
  "Rare Shining",
  "Radiant Rare",
  "Rare ACE",
  "Shiny Ultra Rare",
  "Amazing Rare",
];

// ====================== Yu-Gi-Oh! Constants ======================
export const allTypesYugioh = [
  "Effect Monster",
  "Spell Card",
  "Trap Card",
  "Normal Monster",
  "XYZ Monster",
  "Fusion Monster",
  "Tuner Monster",
  "Link Monster",
  "Synchro Monster",
  "Pendulum Effect Monster",
  "Flip Effect Monster",
  "Skill Card",
  "Ritual Effect Monster",
  "Token",
  "Synchro Tuner Monster",
  "Gemini Monster",
  "Union Effect Monster",
  "Spirit Monster",
  "Pendulum Normal Monster",
  "Toon Monster",
  "Ritual Monster",
  "Pendulum Tuner Effect Monster",
  "Pendulum Effect Fusion Monster",
  "Normal Tuner Monster",
  "XYZ Pendulum Effect Monster",
  "Synchro Pendulum Effect Monster",
  "Pendulum Effect Ritual Monster",
  "Flip Tuner Effect Monster",
  "Pendulum Flip Effect Monster",
];

export const allRaritiesYuGiOh = [
  "Common",
  "Super Rare",
  "Ultra Rare",
  "Rare",
  "Secret Rare",
  "Ultimate Rare",
  "Quarter Century Secret Rare",
  "Platinum Secret Rare",
  "Duel Terminal Normal Parallel Rare",
  "Short Print",
  "Starfoil Rare",
  "Collector's Rare",
  "Prismatic Secret Rare",
  "Gold Rare",
  "Shatterfoil Rare",
  "Mosaic Rare",
  "Duel Terminal Rare Parallel Rare",
  "Starlight Rare",
  "Premium Gold Rare",
  "Gold Secret Rare",
  "Duel Terminal Super Parallel Rare",
  "Duel Terminal Ultra Parallel Rare",
  "Ghost Rare",
  "Ultra Parallel Rare",
  "Starfoil",
  "Platinum Rare",
  "New",
  "Super Short Print",
  "Ultra Rare (Pharaoh's Rare)",
  "Normal Parallel Rare",
  "Reprint",
  "European & Oceanian debut",
  "Extra Secret Rare",
  "Ghost/Gold Rare",
  "2",
  "Super Parallel Rare",
  "Extra Secret",
  "Duel Terminal Normal Rare Parallel Rare",
  "Ultra Secret Rare",
  "Cr",
  "3",
  "Oceanian debut",
  "European debut",
  "10000 Secret Rare",
];